---
# Настройки аутентификации
grafana_admin_user: admin
grafana_admin_password: admin

# Настройки сервера
grafana_http_port: 3000
grafana_domain: localhost
grafana_root_url: "%(protocol)s://%(domain)s:%(http_port)s/"

# Настройки для источников данных
grafana_datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://localhost:9090
    is_default: true
  - name: Loki
    type: loki
    access: proxy
    url: http://localhost:3100
    is_default: false

# Настройки для дашбордов
grafana_dashboards:
  - dashboard_id: 1860
    revision_id: 23
    datasource: Prometheus
    title: Node Exporter Full
  - dashboard_id: 3662
    revision_id: 2
    datasource: Prometheus
    title: Prometheus 2.0 Stats
  - dashboard_id: 13639
    revision_id: 1
    datasource: Loki
    title: Loki Logs 