---
galaxy_info:
  author: DeusOps
  description: Роль для установки и настройки OpenVPN сервера
  company: DeusOps

  license: MIT

  min_ansible_version: 2.9

  platforms:
    - name: Ubuntu
      versions:
        - focal

  galaxy_tags:
    - openvpn
    - vpn
    - security
    - networking

dependencies: [] 