Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.boot_timeout = 600

  # Количество требуемых машин
  SERVERS = 5

  def create_host(config, hostname, ip)
    config.vm.define hostname do |host|
      host.vm.network "private_network", ip: ip
      host.vm.hostname = hostname
      host.vm.provider "virtualbox" do |vb|
        vb.memory = "1024"
        vb.cpus = 1
        vb.check_guest_additions = false
        vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
        vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      end
      host.vm.provision "shell", inline: "apt-get update && apt-get install -y python3-minimal"
      if hostname == "srv1"
        host.vm.network "forwarded_port", guest: 1194, host: 1194, protocol: "udp"
      end
    end
  end

  (1..SERVERS).each do |machine_id|
    create_host(config, "srv#{machine_id}", "192.168.56.#{200+machine_id}")
  end
end 