[web]
web1 ansible_host=192.168.56.201
web2 ansible_host=192.168.56.202

[app]
app1 ansible_host=192.168.56.203
app2 ansible_host=192.168.56.204

[all:vars]
ansible_user=vagrant
ansible_ssh_private_key_file=.vagrant/machines/{{ inventory_hostname }}/virtualbox/private_key
ansible_python_interpreter=/usr/bin/python3 