Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  config.vm.boot_timeout = 600

  # Web сервер 1
  config.vm.define "web1" do |web1|
    web1.vm.hostname = "web1"
    web1.vm.network "private_network", ip: "192.168.56.201"
    web1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.check_guest_additions = false
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    web1.vm.provision "shell", inline: "apt-get update && apt-get install -y python3-minimal"
    web1.vm.network "forwarded_port", guest: 22, host: 7201, id: "ssh_web1", auto_correct: true
  end

  # Web сервер 2
  config.vm.define "web2" do |web2|
    web2.vm.hostname = "web2"
    web2.vm.network "private_network", ip: "192.168.56.202"
    web2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.check_guest_additions = false
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    web2.vm.provision "shell", inline: "apt-get update && apt-get install -y python3-minimal"
    web2.vm.network "forwarded_port", guest: 22, host: 7202, id: "ssh_web2", auto_correct: true
  end

  # App сервер 1
  config.vm.define "app1" do |app1|
    app1.vm.hostname = "app1"
    app1.vm.network "private_network", ip: "192.168.56.203"
    app1.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.check_guest_additions = false
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    app1.vm.provision "shell", inline: "apt-get update && apt-get install -y python3-minimal"
    app1.vm.network "forwarded_port", guest: 22, host: 7203, id: "ssh_app1", auto_correct: true
  end

  # App сервер 2
  config.vm.define "app2" do |app2|
    app2.vm.hostname = "app2"
    app2.vm.network "private_network", ip: "192.168.56.204"
    app2.vm.provider "virtualbox" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
      vb.check_guest_additions = false
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    end
    app2.vm.provision "shell", inline: "apt-get update && apt-get install -y python3-minimal"
    app2.vm.network "forwarded_port", guest: 22, host: 7204, id: "ssh_app2", auto_correct: true
  end
end 